name: CI for the web service

on:
  push:
    paths:
      - "services/web/**"
      - "!services/web/firebase/functions/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            */*/*/node_modules
            */*/*/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Bootstrap all services
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            */*/*/node_modules
            */*/*/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Bootstrap all services
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap
      - name: Deploy the web service
        run: npm run deploy --prefix services/web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
